### ISSUE TITLE
I can't run

### ISSUE THREAD

**Issue by martin823823** [booleanhunter/tasKomplete#1]
If I can't use mongodb ,it,s ok. but, when I open mongodb database, it.s wrong . I thougth it my mongodb's  version need update, i did it .and it still can't run.    seeing the following err log . thanks

macdeMacBook-Pro:tasKomplete-app mac$ node app.js
body-parser deprecated bodyParser: use individual json/urlencoded middlewares configs/server-configs/express-configs.js:29:22
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
express-session deprecated undefined resave option; provide resave option configs/server-configs/express-configs.js:43:25
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option configs/server-configs/express-configs.js:43:25
/Users/mac/tasKomplete/tasKomplete-app/node_modules/mongodb/lib/mongo_client.js:442
          throw err
                ^
Error: dlopen(/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/tasKomplete/tasKomplete-app/controllers/route-handlers/auth-     api-handlers.js:7:14) 
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
  macdeMacBook-Pro:tasKomplete-app mac$

**Comment by booleanhunter** [comment]
@martin823823  could you pull the latest commit and run it once again, then tell me what the logs show?

**Comment by martin823823** [comment]
error still exsit 

macdeMacBook-Pro:tasKomplete-app mac$ node app.js
/Users/mac/tasKomplete/tasKomplete-app/node_modules/mongodb/lib/mongo_client.js:442
          throw err
                ^
Error: dlopen(/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/mac/tasKomplete/tasKomplete-app/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mac/tasKomplete/tasKomplete-app/controllers/route-handlers/auth-api-handlers.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by booleanhunter** [comment]
I think you need to remove your `node_modules` folder, and run `sudo npm install` again. Your issue seems to be related to this - https://github.com/ncb000gt/node.bcrypt.js/issues/84 and this - https://github.com/ncb000gt/node.bcrypt.js/issues/332

Could you do that and let me know once again?

**Comment by martin823823** [comment]
thanks, the question is solved,  but there is a new issue  .   what's "user" ,I can't find it .
macdeMacBook-Pro:tasKomplete-app mac$ node app.js
TypeError: Cannot read property 'user' of undefined
    at Object.renderPage (/Users/mac/tasKomplete/tasKomplete-app/controllers/route-handlers/auth-api-handlers.js:14:19)
    at /Users/mac/tasKomplete/tasKomplete-app/controllers/routes/auth-api.js:73:25
    at Layer.handle [as handle_request] (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:271:10)
    at session (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express-session/index.js:159:61)
    at Layer.handle [as handle_request] (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:312:13)
    at /Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mac/tasKomplete/tasKomplete-app/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/Users/mac/tasKomplete/tasKomplete-app/node_modules/body-parser/lib/types/urlencoded.js:88:40)

**Comment by booleanhunter** [comment]
- Do you have Redis installed in your system? If not, then installing that would solve the issue - http://redis.io/topics/quickstart

- If Redis is installed, verify whether you have these lines in `configs/server-configs/express-configs.js`, in this order ? 

```javascript
expressInstance.use(cookieParser());

expressInstance.use(expressSession({ 

        store: new RedisStore({
            host: 'localhost',
            port: 6379,
            db: 2,
            ttl: 60 * 60 * 24 * 365
        }), 
        secret: 'booleanhunter', 
        resave: true, 
        saveUninitialized: true 
    }));
```

According to these links [here](http://stackoverflow.com/questions/10191692/session-is-undefined-when-using-express-redis-for-session-store), and [here](http://stackoverflow.com/questions/12714999/nodejs-express-redisstore-req-session-undefined), the above lines should be in the same order.

**Comment by martin823823** [comment]
thanks very much.  I  had sovled it. I could't install redis before.  thank you.

**Comment by martin823823** [comment]
where is  user data ? I can't find it in redis database.  data is saved mongodb?

**Comment by booleanhunter** [comment]
Yes. Data is saved in mongoDB. Type the following commands in a terminal -

- Type `mongo` This will open up a MongoDB client interface
- Next, switch to the DB we're using for our application, in our case it's todoAppDB. Run `use todoAppDB`. To display all dbs, run `show dbs`
- Next, `show collections` will show you all collections existing. Type `db.userData.find().pretty()` to see  user data.

It will be helpful if you go through the [official mongodb documentation](https://docs.mongodb.org/manual/reference/command/#query-and-write-operation-commands) first.

To see sessions stored in redis, run `redis-cli monitor` before you login. Upon login, you'll see session variables getting saved to redis.

**Comment by martin823823** [comment]
so, thanks very much . thank you .  I like node.js ,  can you tell me how to learn node.js about you,  please.  
I think my ways is incorrect .
